@startuml
package ScaFi-core {
  interface "FieldCalculusSyntax" as FCS
  interface "RoundVM" as RVM
}

package ScaFi-Fields {
  package field {
    interface "Fields" as F
    package lang {
      interface "FieldLanguage" as FL
      interface "FieldLangImpl" as FLI
    }
    package syntax {
      interface "FieldsSyntax" as FS
    }
  }
}


FS --* F
F *-- FL
FCS *-- F
FLI --|> FL
FLI --* RVM

@enduml